language: cpp
matrix:
  include:
  - os: osx
    env: OS_BUILD=osx
  - os: linux
    env: OS_BUILD=linux FOLDER=x64
    dist: xenial
    arch: amd64
    sudo: required
    before_install:
    - sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
      libcups2-dev libxrandr-dev libasound2 libasound2-dev
  - os: linux
    env: OS_BUILD=linux FOLDER=aarch64
    dist: xenial
    arch: arm64
    sudo: required
    before_install:
    - sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
      libcups2-dev libxrandr-dev libasound2 libasound2-dev zip
  - os: windows
    env: OS_BUILD=windows
    before_install:
    - choco install cygwin
    - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip
before_script:
  - if [[ $OS_BUILD == "windows" ]]; then
      git config --system core.longpaths true;
      git config --global core.autocrlf false;
    fi
  - unset -v _JAVA_OPTIONS;
  - git clone --depth 1 --branch travaopenjdk https://github.com/TravaOpenJDK/openjdk-build.git;
script:
  - export SOURCE_JDK_TAG=dcevm-11.0.10+4
  - export HSWAP_AGENT_DOWNLOAD_URL=https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-1.4.1.jar
  - export HSWAP_AGENT_CORE_DOWNLOAD_URL=https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-core-1.4.1.jar
  - export JDK_BOOT_DIR="$PWD/openjdk-build/jdk-11"
  - mkdir -p "$JDK_BOOT_DIR"
  - if [[ $OS_BUILD == "linux" ]]; then
      wget -q -O - "https://api.adoptopenjdk.net/v3/binary/version/jdk-11.0.4%2B11/linux/${FOLDER}/jdk/hotspot/normal/adoptopenjdk?project=jdk" | tar xpzf - --strip-components=1 -C ${JDK_BOOT_DIR};
      export JAVA_HOME="${JDK_BOOT_DIR}";
    fi
  - if [[ $OS_BUILD == "osx" ]]; then
      wget -q -O - 'https://api.adoptopenjdk.net/v3/binary/version/jdk-11.0.4%2B11/mac/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk' | tar xpzf - --strip-components=2 -C ${JDK_BOOT_DIR};
      export JDK_BOOT_DIR=${JDK_BOOT_DIR}/Home;
      export JAVA_HOME="${JDK_BOOT_DIR}";
    fi
  - echo ${SOURCE_JDK_TAG}
  - if [[ $OS_BUILD == "linux" || $OS_BUILD == "osx" ]]; then
      bash -c "cd openjdk-build && export LOG=info && ./makejdk-any-platform.sh --tag \"${SOURCE_JDK_TAG}\" --build-variant dcevm --branch dcevm11-jdk-11.0.10-adopt --disable-test-image
        --jdk-boot-dir ${JDK_BOOT_DIR} --hswap-agent-download-url \"${HSWAP_AGENT_DOWNLOAD_URL}\" --hswap-agent-core-download-url \"${HSWAP_AGENT_CORE_DOWNLOAD_URL}\" --configure-args '-disable-warnings-as-errors' 
        --target-file-name java11-openjdk-dcevm-${TRAVIS_OS_NAME}.tar.gz jdk11u";
    fi
  - if [[ $OS_BUILD == "windows" ]]; then
      powershell -Command "C:\tools\cygwin\bin\bash.exe -c './build_windows.sh'";
    fi
deploy:
  provider: releases
  api_key:
    secure: "JyoyNC8EvKk66KIs49wR5jjAsn95ivvznpQVFBOqIIBFpzq6WE108lkfvX7u3Y9YfHpcu2nbaZOVuXsyUx5ZZ+yKwNZGfsPwkFYqHmO8Nh0y9gSYbzfTlabkTP+DO+4XVVJpV0P7vOcjiT1ThNZIyWUyhpjx05riur3e8N2bVlpgWOJBxztNvC4E9F2wy0BwyKjXipjFIVl1JGBeG86h78r3NpOlIrmU0/npN5W416CPjauOOyKCKpApzFU8WuxLOAX0KmXNShS0X5ZABQ6Ur4YYlu9+DuHSLvvWhhRQWYdUu+TFYklpMedKWsU4hosN2k3aUpjvwX2/kF7KHcSmN0/37CbQfJneGwfB8f3ilOq4cM3inc9bQhsQFlWJAAu+MJ/hGV2pSeWoxDDE3UvjE06+sIiTd3mYwIiy7N4F3zdCzPzHbAMFeQoeS18clTRXdhv30h+hUi232TzJjqRdzcJFqklf5U3VNDEyv4iJDo0SnxpfwZcbBuA/cCHe38McSm1vtc0zfvLxegbBkQKjf/7VE9o2VHNelibuYsD2UdsbpRpBvA9QxWhvFF/h4FEJZO60gOv2ec9SO9vLzZJT7ZlHEQQVkonjpeEhu1t88fNqiaxU7oc2VB6/x1eWt25pwsRz0GDZviY0epXzlCmwmK2qSQwl55qiR5MKF/Bzc6c="
  file_glob: true
  file: openjdk-build/workspace/target/*
  skip_cleanup: true
  overwrite: true
  on:
    repo: markdbuck/trava-jdk-11-dcevm
    all_branches: true
    tags: true
