language: cpp
matrix:
  include:
  - os: osx
    env: OS_BUILD=osx
  - os: linux
    env: OS_BUILD=linux FOLDER=x64
    dist: xenial
    arch: amd64
    sudo: required
    before_install:
    - sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
      libcups2-dev libxrandr-dev libasound2 libasound2-dev
  - os: linux
    env: OS_BUILD=linux FOLDER=aarch64
    dist: xenial
    arch: arm64
    sudo: required
    before_install:
    - sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
      libcups2-dev libxrandr-dev libasound2 libasound2-dev zip
  - os: windows
    env: OS_BUILD=windows
    before_install:
    - choco install cygwin
    - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip
before_script:
  - if [[ $OS_BUILD == "windows" ]]; then
      git config --system core.longpaths true;
      git config --global core.autocrlf false;
    fi
  - unset -v _JAVA_OPTIONS;
  - git clone --depth 1 --branch travaopenjdk https://github.com/TravaOpenJDK/openjdk-build.git;
script:
  - export SOURCE_JDK_TAG=dcevm-11.0.11+1
  - export HSWAP_AGENT_DOWNLOAD_URL=https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-1.4.1.jar
  - export HSWAP_AGENT_CORE_DOWNLOAD_URL=https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-core-1.4.1.jar
  - export JDK_BOOT_DIR="$PWD/openjdk-build/jdk-11"
  - mkdir -p "$JDK_BOOT_DIR"
  - if [[ $OS_BUILD == "linux" ]]; then
      wget -q -O - "https://api.adoptopenjdk.net/v3/binary/version/jdk-11.0.4%2B11/linux/${FOLDER}/jdk/hotspot/normal/adoptopenjdk?project=jdk" | tar xpzf - --strip-components=1 -C ${JDK_BOOT_DIR};
      export JAVA_HOME="${JDK_BOOT_DIR}";
    fi
  - if [[ $OS_BUILD == "osx" ]]; then
      wget -q -O - 'https://api.adoptopenjdk.net/v3/binary/version/jdk-11.0.4%2B11/mac/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk' | tar xpzf - --strip-components=2 -C ${JDK_BOOT_DIR};
      export JDK_BOOT_DIR=${JDK_BOOT_DIR}/Home;
      export JAVA_HOME="${JDK_BOOT_DIR}";
    fi
  - echo ${SOURCE_JDK_TAG}
  - if [[ $OS_BUILD == "linux" || $OS_BUILD == "osx" ]]; then
      bash -c "cd openjdk-build && export LOG=info && ./makejdk-any-platform.sh --tag \"${SOURCE_JDK_TAG}\" --build-variant dcevm --branch dcevm11-jdk-11.0.11-adopt --disable-test-image
        --jdk-boot-dir ${JDK_BOOT_DIR} --hswap-agent-download-url \"${HSWAP_AGENT_DOWNLOAD_URL}\" --hswap-agent-core-download-url \"${HSWAP_AGENT_CORE_DOWNLOAD_URL}\" --configure-args '-disable-warnings-as-errors' 
        --target-file-name java11-openjdk-dcevm-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}.tar.gz jdk11u";
    fi
  - if [[ $OS_BUILD == "windows" ]]; then
      powershell -Command "C:\tools\cygwin\bin\bash.exe -c './build_windows.sh'";
    fi
deploy:
  provider: releases
  api_key:
    secure: "JFfRTJThITCLkSEeGc3SG62p20tuBMknmsBNK32+p0SCwdqFDJn45eXTzlIavJtixE4GrEBZHm+okJRIM7rMYJYUkPkCeQaggSYRuXTKTE6Ojcfpw6XSG4lMApocgvT9vlqW7kdjuvdKxm020TcyxATsuUcoUl+ENnVtIzAH9W3z0L9XHK2woL3CenFYCJJ+QPrjpvG93RgVhFHzioSp5Md1Nqk7MUDPj/VigFpyOuU6s4U5Wyf72JW7PbSy9sbXjTcCf0GcrhdsUslYg7v6/nqITIg+a1Zy70O7rT2pHElWDZ7jOKZYG4h3TayexsJKOiQSVH1Mp9siGOxwf0wsbMGQSwxCPmiUFdTEEyAwyndNtSzFNZjrWjnNauEL3v3kBiS7nkAgp0wDgQ+EFujXu/CH5vOvbiA26kj4lucku+6Qfb3luQk2MYEqNuiI/NZ2folp8fmzEcoiCUiVLxR8c0tboW2nkb3IzxNsvAazwmkUZGMeVzyFH7g8fUa3hRPVtypD5zsM/3pya7letE5z/K3G3fPVy/grTbjPf+UyKC3pM6IAi1+Mwu4cVdC2q2DYCpFDGwhzhdGGBWYdOkepmBxkQc7WtYha8vFr6uA1LdkbMKHgknODxqR4X0Hc3xtg2i2wKOU56UFtyHvOU6YEml6GWlPGFCjThWxbH40A+5A="
  file_glob: true
  file: openjdk-build/workspace/target/*
  skip_cleanup: true
  overwrite: true
  on:
    repo: TravaOpenJDK/trava-jdk-11-dcevm
    tags: true
