language: cpp
env:
  SOURCE_JDK_TAG=dcevm-11.0.1+1
matrix:
  include:
  - os: osx
  - os: linux
    dist: xenial
    sudo: required
    before_install:
    - sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
      libcups2-dev libasound2
    - sudo ln -s /usr/lib/x86_64-linux-gnu/libasound.so.2 /usr/lib/x86_64-linux-gnu/libasound.so
  - os: windows
    before_install:
    - choco install cygwin
    - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip
before_script:
  - if [[ $os_build == "linux" || $os_build == "osx" ]]; then
      unset -v _JAVA_OPTIONS;
      wget https://github.com/sormuras/bach/raw/master/install-jdk.sh;
      git clone --depth 1 https://github.com/TravaOpenJDK/openjdk-build.git;
    fi
  - if [[ $os_build == "windows" ]]; then
      unset -v _JAVA_OPTIONS;
      git config --system core.longpaths true;
      git config --global core.autocrlf false;
      git clone --depth 1 https://github.com/skybber/openjdk-build.git;
    fi
script:
  - if [[ $os_build == "linux" || $os_build == "osx" ]]; then
      source install-jdk.sh -f 10;
      bash -c "cd openjdk-build && export LOG=info && ./makejdk-any-platform.sh  --tag ${SOURCE_JDK_TAG} --build-variant
        dcevm --branch dcevm11 --configure-args '-disable-warnings-as-errors' --target-file-name java11-openjdk-dcevm-${TRAVIS_OS_NAME}.tar.gz jdk11u";
    fi
  - if [[ $os_build == "windows" ]]; then
      powershell -Command "C:\tools\cygwin\bin\bash.exe -c './build_windows.sh'";
    fi
deploy:
  provider: releases
  api_key:
    secure: GM7UyxAw/l78Li2AcKb8DE+cLblDaDdk4sQ7QZZ5gqyRxy87GM6lKZpeZ7Io9tiXEhLppxOmE2q5pXRSQOR6TzVN7FFJp8q6a19rla8Tbrf9/cfNUEv1YZENpBzzCJTNYyBWeTU7P6LG0PkAxoNa424Wi3cPwyZTUlz5lM0a0rL3OMHNWMpLDowXYefsgkI9YLaOU2yaR/EBMP63O0UsH2Zhq5pgjTHJvFyWTVC0F7P82LDDsMMMu1x0ATntd9S+vSSd1ir5pfFJc9ll1qT57U8LGL8sUMRGixVigTelcUr4W2C3w23cMsDV5pejqb8Em02wkgHRQPgtD34EE4xIt3VVbDxWrUYKpX7E9Wcvd1PWxppL0WABHP38/bSmoh0OyU0Chf+exYbraomui2eGPexbjURHlzwxzCtx7z9w+mHAphtcRUV64QWPWzzksnUcrbcrfz1XzyL2PaZMUnhmm4Ti+pslqdAPZi13BF6bvnlS2lKm9A0EF3t/xS4vBuX4md9ZRHbLWSZC17jHo2b2HgpJvyIZxfopp8+5HHN0hyFqB/muApNlga5mANie91/pIVcAo+xfsInMgag0xmzPwgJkIKfEbC6zaNkp/ODuE8FWT5lzkzysGjB0VHHH2UWmpQ/LNrS6grxK4BbtXB2xM1Tl7VyKpD4pnFyLkHFt6VE=
  file_glob: true
  file: openjdk-build/workspace/target/*
  skip_cleanup: true
  on:
    repo: TravaOpenJDK/trava-jdk-11-dcevm
    all_branches: true
    tags: true
