language: cpp
matrix:
  include:
  - os: linux
    env: OS_BUILD=linux
    dist: xenial
    arch: arm64
    sudo: required
    before_install:
    - sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
      libcups2-dev libxrandr-dev libasound2 libasound2-dev zip
before_script:
  - if [[ $OS_BUILD == "windows" ]]; then
      git config --system core.longpaths true;
      git config --global core.autocrlf false;
    fi
  - unset -v _JAVA_OPTIONS;
  - git clone --depth 1 --branch travaopenjdk https://github.com/TravaOpenJDK/openjdk-build.git;
script:
  - export SOURCE_JDK_TAG=dcevm-11.0.10+4
  - export HSWAP_AGENT_DOWNLOAD_URL=https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-1.4.1.jar
  - export HSWAP_AGENT_CORE_DOWNLOAD_URL=https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-core-1.4.1.jar
  - export JDK_BOOT_DIR="$PWD/openjdk-build/jdk-11"
  - mkdir -p "$JDK_BOOT_DIR"
  - if [[ $OS_BUILD == "linux" ]]; then
      wget -q -O - "https://api.adoptopenjdk.net/v3/binary/version/jdk-11.0.4%2B11/linux/aarch64/jdk/hotspot/normal/adoptopenjdk?project=jdk" | tar xpzf - --strip-components=1 -C ${JDK_BOOT_DIR};
      ls -l ${JDK_BOOT_DIR};
      export JAVA_HOME="${JDK_BOOT_DIR}";
    fi
  - if [[ $OS_BUILD == "osx" ]]; then
      wget -q -O - 'https://api.adoptopenjdk.net/v3/binary/version/jdk-11.0.4%2B11/mac/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk' | tar xpzf - --strip-components=2 -C ${JDK_BOOT_DIR};
      export JDK_BOOT_DIR=${JDK_BOOT_DIR}/Home;
      export JAVA_HOME="${JDK_BOOT_DIR}";
    fi
  - echo ${SOURCE_JDK_TAG}
  - if [[ $OS_BUILD == "linux" || $OS_BUILD == "osx" ]]; then
      bash -c "cd openjdk-build && export LOG=info && ./makejdk-any-platform.sh --tag \"${SOURCE_JDK_TAG}\" --build-variant dcevm --branch dcevm11-jdk-11.0.10-adopt --disable-test-image
        --jdk-boot-dir ${JDK_BOOT_DIR} --hswap-agent-download-url \"${HSWAP_AGENT_DOWNLOAD_URL}\" --hswap-agent-core-download-url \"${HSWAP_AGENT_CORE_DOWNLOAD_URL}\" --configure-args '-disable-warnings-as-errors' 
        --target-file-name java11-openjdk-dcevm-${TRAVIS_OS_NAME}.tar.gz jdk11u";
    fi
  - if [[ $OS_BUILD == "windows" ]]; then
      powershell -Command "C:\tools\cygwin\bin\bash.exe -c './build_windows.sh'";
    fi
deploy:
  provider: releases
  api_key:
    secure: "WsV1KT9UIDo6TsoPZzAvoLGr2bZk4GZ1VuEoFSJxyyEnZRCV7g8ROrFVPq6vskkjotfoM5qnGSMSWUWKhJw+yqvtvXCa0zpsnQ8lBTJiJg656ke9RzdQZSDRtwBF7JWCZx8/JRM0WckzXHqgmdUWt/gO0RYLzDD/Mq/6XDHQ43ttjyX4T9oPBsLvM/SmOriJEtOETtmbttXxVRte4RSzWL9/soe9uhTUu36R0qEO3peUZ9i145Me6UmUiwH+5thFuKQtajOZFzBa5ZysmX9ZxI43LjI18Xwa/MAlKQBYbrQKNB8VhUkoHJ4AHCrUXX8DAIIo4xH62FXEE+Wi5xoIlLhGcJWBVZ94GOhktLxe2iAgrqt09iOjfZmwHsQS6fw9RjHtyxRLCAlQSYWIWY+xe60VSrioF7i87J+JUnDYARNNMhAHThwtrZs2KmnfxH2PY3AQY6061XLWgsi1Dr9DXLYxmI/WwfaNEtJs68r5InbTS8za7MzVH+7/jqy6/lDpsl9DEKCqx8Q0qbp/B0ayq1YNKRqGJOIK98RwUzvdaF2BG285U3T7gK1MrnKJK5UZ4Sr+zZPvMpWVHT0Xadk/YEKdGcIpL9LfmpWVtbRaY0oavXtsNVTzoawYpcV0qWC4uqZ6/74igcw4eDYWxIxxPHxA9aKSLdPvZW2TruVJanc="
  file_glob: true
  file: openjdk-build/workspace/target/*
  skip_cleanup: true
  overwrite: true
  on:
    repo: markdbuck/trava-jdk-11-dcevm
    all_branches: true
    tags: true
